### ISSUE TITLE
Building as a dependency error

### ISSUE THREAD

**Issue by TatriX** [justinwoo/purescript-lenient-html-parser#1]
Hello. I have a problem building the parser.
```sh
mkdir test
cd test
pulp init
pulp test # wors fine
bower install purescript-lenient-html-parser
pulp test
```
gives an error:
```
Error found:
in module LenientHtmlParser
at bower_components/purescript-lenient-html-parser/src/LenientHtmlParser.purs line 8, column 1 - line 8, column 36

  Module Data.Generic was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.
```

If I clone the repo itself and run `pulp test` everything works fine though.

What am I doing wrong?

**Comment by TatriX** [comment]
Hm, I ran
```sh
bower install purescript-generics
```
and it seems to work now. Probably it should be done automatically?

**Comment by justinwoo** [comment]
sorry, haven't seen this issue because github didn't subscribe me... :(

yeah, need to fix this mistake. sorry!

**Comment by justinwoo** [comment]
pushed up 1.0.0 without Generic!

**Comment by TatriX** [comment]
Thanks!
